//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicDate.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelBindingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelBindingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xefiros.Server.Resources.ModelBindingResource", typeof(ModelBindingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty request body is required..
        /// </summary>
        public static string A_non_empty_request_body_is_required_ {
            get {
                return ResourceManager.GetString("A non-empty request body is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for the &apos;{0}&apos; parameter or property was not provided..
        /// </summary>
        public static string A_value_for_the___0___parameter_or_property_was_not_provided_ {
            get {
                return ResourceManager.GetString("A value for the \'{0}\' parameter or property was not provided.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required..
        /// </summary>
        public static string A_value_is_required_ {
            get {
                return ResourceManager.GetString("A value is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a number..
        /// </summary>
        public static string The_field__0__must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field {0} must be a number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string The_field_must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field must be a number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid..
        /// </summary>
        public static string The_supplied_value_is_invalid_ {
            get {
                return ResourceManager.GetString("The supplied value is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid for {0}..
        /// </summary>
        public static string The_supplied_value_is_invalid_for__0__ {
            get {
                return ResourceManager.GetString("The supplied value is invalid for {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string The_value___0___is_invalid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid..
        /// </summary>
        public static string The_value___0___is_not_valid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for {1}..
        /// </summary>
        public static string The_value___0___is_not_valid_for__1__ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid for {1}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be null.
        /// </summary>
        public static string The_value_must_not_be_null {
            get {
                return ResourceManager.GetString("The value must not be null", resourceCulture);
            }
        }
    }
}
