//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicDate.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xefiros.Server.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login already exists..
        /// </summary>
        public static string A_user_with_this_login_already_exists_ {
            get {
                return ResourceManager.GetString("A user with this login already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string An_unknown_failure_has_occurred_ {
            get {
                return ResourceManager.GetString("An unknown failure has occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already taken..
        /// </summary>
        public static string Email__0__is_already_taken_ {
            get {
                return ResourceManager.GetString("Email {0} is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is invalid..
        /// </summary>
        public static string Email__0__is_invalid_ {
            get {
                return ResourceManager.GetString("Email {0} is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string Incorrect_password_ {
            get {
                return ResourceManager.GetString("Incorrect password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string Passwords_must_be_at_least__0__characters_ {
            get {
                return ResourceManager.GetString("Passwords must be at least {0} characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string Passwords_must_have_at_least_one_digit___0___9___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one digit (\'0\'-\'9\').", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string Passwords_must_have_at_least_one_lowercase___a___z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one lowercase (\'a\'-\'z\').", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string Passwords_must_have_at_least_one_non_alphanumeric_character_ {
            get {
                return ResourceManager.GetString("Passwords must have at least one non alphanumeric character.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string Passwords_must_have_at_least_one_uppercase___A___Z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one uppercase (\'A\'-\'Z\').", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name {0} is already taken..
        /// </summary>
        public static string Role_name__0__is_already_taken_ {
            get {
                return ResourceManager.GetString("Role name {0} is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name {0} is invalid..
        /// </summary>
        public static string Role_name__0__is_invalid_ {
            get {
                return ResourceManager.GetString("Role name {0} is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string The_Password_field_is_required_ {
            get {
                return ResourceManager.GetString("The Password field is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password set..
        /// </summary>
        public static string User_already_has_a_password_set_ {
            get {
                return ResourceManager.GetString("User already has a password set.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role {0}..
        /// </summary>
        public static string User_already_in_role__0__ {
            get {
                return ResourceManager.GetString("User already in role {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name {0} is already taken..
        /// </summary>
        public static string User_Name__0__is_already_taken_ {
            get {
                return ResourceManager.GetString("User Name {0} is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name {0} is invalid, can only contain letters or digits..
        /// </summary>
        public static string User_name__0__is_invalid__can_only_contain_letters_or_digits_ {
            get {
                return ResourceManager.GetString("User name {0} is invalid, can only contain letters or digits.", resourceCulture);
            }
        }
    }
}
